name: Validate the Board

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python3
      uses: actions/setup-python@v1
      with:
        version: '3.7'
        architecture: 'x64'
    - name: Install Numpy 
      run: pip3 install numpy
    - name: Validate
      run: cd board && make test PYTHON=python3 TARGET_DIR="*"
